name: citiguide_user
description: "a city travel guide."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  maps_launcher: ^3.0.0+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shared_preferences: ^2.3.4
  internet_connection_checker: ^3.0.1
  flutter_native_splash: ^2.4.4
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
