// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBODcYUfTnNPkNvDhalkF-hJoTjqlLXup8',
    appId: '1:939090159514:web:7ce03700e6536cf8f87c23',
    messagingSenderId: '939090159514',
    projectId: 'citiguide-f8f31',
    authDomain: 'citiguide-f8f31.firebaseapp.com',
    storageBucket: 'citiguide-f8f31.firebasestorage.app',
    measurementId: 'G-C3R02GPLQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnbNbiRIKRCYMQD5KpZzmMcKDBFlDIAJE',
    appId: '1:939090159514:android:20d0afe4691f5f4bf87c23',
    messagingSenderId: '939090159514',
    projectId: 'citiguide-f8f31',
    storageBucket: 'citiguide-f8f31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYwiGG26z7wYz1wCiywhPl1zn9tgZzmY',
    appId: '1:939090159514:ios:fc1c6ebb584337ddf87c23',
    messagingSenderId: '939090159514',
    projectId: 'citiguide-f8f31',
    storageBucket: 'citiguide-f8f31.firebasestorage.app',
    iosBundleId: 'com.example.citiguideUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfYwiGG26z7wYz1wCiywhPl1zn9tgZzmY',
    appId: '1:939090159514:ios:fc1c6ebb584337ddf87c23',
    messagingSenderId: '939090159514',
    projectId: 'citiguide-f8f31',
    storageBucket: 'citiguide-f8f31.firebasestorage.app',
    iosBundleId: 'com.example.citiguideUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBODcYUfTnNPkNvDhalkF-hJoTjqlLXup8',
    appId: '1:939090159514:web:050e74c4bb43c88ef87c23',
    messagingSenderId: '939090159514',
    projectId: 'citiguide-f8f31',
    authDomain: 'citiguide-f8f31.firebaseapp.com',
    storageBucket: 'citiguide-f8f31.firebasestorage.app',
    measurementId: 'G-H4MNBJ9GN8',
  );

}